// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: pkg/proto/server/server.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileProtoService_CreateDonorProfile_FullMethodName = "/ProfileProtoService/CreateDonorProfile"
)

// ProfileProtoServiceClient is the client API for ProfileProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileProtoServiceClient interface {
	CreateDonorProfile(ctx context.Context, in *CreateDonorProfileRequestDto, opts ...grpc.CallOption) (*CreateDonorProfileResponseDto, error)
}

type profileProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileProtoServiceClient(cc grpc.ClientConnInterface) ProfileProtoServiceClient {
	return &profileProtoServiceClient{cc}
}

func (c *profileProtoServiceClient) CreateDonorProfile(ctx context.Context, in *CreateDonorProfileRequestDto, opts ...grpc.CallOption) (*CreateDonorProfileResponseDto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDonorProfileResponseDto)
	err := c.cc.Invoke(ctx, ProfileProtoService_CreateDonorProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileProtoServiceServer is the server API for ProfileProtoService service.
// All implementations must embed UnimplementedProfileProtoServiceServer
// for forward compatibility.
type ProfileProtoServiceServer interface {
	CreateDonorProfile(context.Context, *CreateDonorProfileRequestDto) (*CreateDonorProfileResponseDto, error)
	mustEmbedUnimplementedProfileProtoServiceServer()
}

// UnimplementedProfileProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileProtoServiceServer struct{}

func (UnimplementedProfileProtoServiceServer) CreateDonorProfile(context.Context, *CreateDonorProfileRequestDto) (*CreateDonorProfileResponseDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDonorProfile not implemented")
}
func (UnimplementedProfileProtoServiceServer) mustEmbedUnimplementedProfileProtoServiceServer() {}
func (UnimplementedProfileProtoServiceServer) testEmbeddedByValue()                             {}

// UnsafeProfileProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileProtoServiceServer will
// result in compilation errors.
type UnsafeProfileProtoServiceServer interface {
	mustEmbedUnimplementedProfileProtoServiceServer()
}

func RegisterProfileProtoServiceServer(s grpc.ServiceRegistrar, srv ProfileProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedProfileProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileProtoService_ServiceDesc, srv)
}

func _ProfileProtoService_CreateDonorProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDonorProfileRequestDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileProtoServiceServer).CreateDonorProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileProtoService_CreateDonorProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileProtoServiceServer).CreateDonorProfile(ctx, req.(*CreateDonorProfileRequestDto))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileProtoService_ServiceDesc is the grpc.ServiceDesc for ProfileProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProfileProtoService",
	HandlerType: (*ProfileProtoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDonorProfile",
			Handler:    _ProfileProtoService_CreateDonorProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/server/server.proto",
}
